# Generated by Django 5.2 on 2025-05-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares_inventario', '0002_delete_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_minimo', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('Subcatalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares_inventario.subcatalogo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares_inventario.unidaddemedida')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nota', models.TextField(blank=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('herencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.herencia')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30)),
                ('fecha_folio', models.DateField()),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
    ]
