# Generated by Django 5.2 on 2025-05-31 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares_inventario', '0002_delete_proveedor'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares_inventario.marca'),
        ),
    ]
