# Generated by Django 5.2 on 2025-05-31 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='producto',
        ),
        migrations.CreateModel(
            name='EntradaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.entrada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
    ]
