# Generated by Django 5.2 on 2025-06-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares_inventario', '0002_delete_proveedor'),
        ('inventario', '0003_remove_entrada_cantidad_remove_entrada_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herencia',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='herencia',
            new_name='tipo',
        ),
    ]
