# Generated by Django 5.2 on 2025-06-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_entrada_folio_entrada_unique_folio_nonblank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha_folio',
            new_name='fecha_recepcion',
        ),
    ]
