# Generated by Django 5.2 on 2025-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_fecha_folio_entrada_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
