# Generated by Django 5.2 on 2025-06-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_entrada_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de serie'),
        ),
    ]
