# Generated by Django 5.2 on 2025-06-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_producto_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_hijos', to='inventario.producto'),
        ),
    ]
