# Generated by Django 5.2 on 2025-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_producto_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_serie',
            field=models.BooleanField(default=False, verbose_name='¿Este producto tendrá unidades con serie (hijos)?'),
        ),
    ]
