# Generated by Django 5.2 on 2025-05-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares_inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
