# Generated by Django 5.2 on 2025-07-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0011_producto_producto_parent_child_consistency'),
        ('solicitantes', '0005_alter_solicitante_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('vale_pdf', models.FileField(blank=True, null=True, upload_to='vales_pdf/')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitantes.departamento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitantes.solicitante')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitantes.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='ValeDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='salidas.valesalida')),
            ],
        ),
    ]
