# Generated by Django 5.2 on 2025-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='departamento',
        ),
        migrations.AddField(
            model_name='unidad',
            name='departamentos',
            field=models.ManyToManyField(to='solicitantes.departamento'),
        ),
    ]
