# Generated by Django 5.2 on 2025-05-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0002_remove_unidad_departamento_unidad_departamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='departamentos',
            field=models.ManyToManyField(related_name='unidades', to='solicitantes.departamento'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitantes.cargo'),
        ),
    ]
