# Generated by Django 5.2 on 2025-05-19 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0003_cargo_alter_solicitante_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento dentro de la unidad seleccionada', null=True, on_delete=django.db.models.deletion.PROTECT, to='solicitantes.departamento'),
        ),
    ]
