# Generated by Django 5.2 on 2025-05-19 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0004_solicitante_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='departamento',
            field=models.ForeignKey(default=1, help_text='Departamento dentro de la unidad seleccionada', on_delete=django.db.models.deletion.PROTECT, to='solicitantes.departamento'),
            preserve_default=False,
        ),
    ]
