# Generated by Django 5.2 on 2025-05-10 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciasLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('id_registro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dato', models.IntegerField()),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('id_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accion')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.modulo')),
                ('id_ref_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.referenciaslog')),
            ],
        ),
    ]
